### ISSUE TITLE
NPE on List.size();

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/Quotes#65]
**Describe the bug**
App crashed unexpectedly. (When opened app 2nd time, just after testing #6 Not sure if it's related)
Probably 1 time crash.

**Crash logs**
```
FATAL EXCEPTION: main
Process: phone.vishnu.quotes, PID: 21989
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at y4.l.c(Unknown Source:2)
	at androidx.viewpager.widget.ViewPager.e(Unknown Source:2)
	at androidx.viewpager.widget.ViewPager$j.onChanged(Unknown Source:2)
	at f1.a.d(Unknown Source:5)
	at x4.c.publishResults(SourceFile:4)
	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Smartphone (please complete the following information):**
 - Device: `Lenovo Tab4 8 plus`
 - Andorid Version: `8.1.0`
 - App Version: `2.6.0 (50)`

**Comment by VishnuSanal** [comment]
@shuvashish76 So, you changed to landscape with that app?

**Comment by shuvashish76** [comment]
Yes
